2021-04-05T13:08:47.322+0800 I CONTROL  [initandlisten] MongoDB starting : pid=50 port=27017 dbpath=/data/db 64-bit host=v_yuuhan-NB1
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten] db version v3.6.3
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten] git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten] allocator: tcmalloc
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten] modules: none
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten] build environment:
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten]     distarch: x86_64
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten]     target_arch: x86_64
2021-04-05T13:08:47.323+0800 I CONTROL  [initandlisten] options: {}
2021-04-05T13:08:47.325+0800 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
2021-04-05T13:08:47.329+0800 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2021-04-05T13:08:47.329+0800 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2021-04-05T13:08:47.330+0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7504M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2021-04-05T13:08:48.698+0800 I STORAGE  [initandlisten] WiredTiger message [1617599328:698229][50:0x7f705aa810c0], txn-recover: Main recovery loop: starting at 34/3200
2021-04-05T13:08:48.700+0800 I STORAGE  [initandlisten] WiredTiger message [1617599328:700102][50:0x7f705aa810c0], txn-recover: Recovering log 34 through 35
2021-04-05T13:08:48.851+0800 I STORAGE  [initandlisten] WiredTiger message [1617599328:851895][50:0x7f705aa810c0], txn-recover: Recovering log 35 through 35
2021-04-05T13:08:49.045+0800 I CONTROL  [initandlisten] 
2021-04-05T13:08:49.045+0800 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2021-04-05T13:08:49.045+0800 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2021-04-05T13:08:49.045+0800 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2021-04-05T13:08:49.045+0800 I CONTROL  [initandlisten] 
2021-04-05T13:08:49.045+0800 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2021-04-05T13:08:49.046+0800 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2021-04-05T13:08:49.046+0800 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2021-04-05T13:08:49.046+0800 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2021-04-05T13:08:49.046+0800 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2021-04-05T13:08:49.046+0800 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2021-04-05T13:08:49.046+0800 I CONTROL  [initandlisten] 
2021-04-05T13:08:49.074+0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2021-04-05T13:08:49.076+0800 I NETWORK  [initandlisten] waiting for connections on port 27017
2021-04-05T13:08:50.058+0800 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
